blank_issues_enabled: true
contact_links:
  - name: Telegram Support Group
    url: https://t.me/Material_You_NewTab
    about: Join our Telegram group for quick support and discussions.
  - name: Contribution Guidelines
    url: https://github.com/prem-k-r/MaterialYouNewTab/blob/main/CONTRIBUTING.md
    about: Learn how to contribute to Material You New Tab.
